### ISSUE TITLE
Determine architecture

### ISSUE THREAD

**Issue by rguilmain** [rguilmain/Tacktx#10]
@tderensis @timothy-a-bertram Plenty of changes to come! My current thought is that anything our source code will need to import should live somewhere under src. Because our assets will be imported by our source code, I'm putting them in src/assets. Similarly, I'm planning on dividing our current collection of third party tools into src/third_party for importable modules (i.e. middleclass and any other lua libraries we'll want to use), and a top-level third_party outside of src for utilities we need for the build process, etc. (i.e. love and 7zip). Let me know if you have any questions or comments.

**Comment by rguilmain** [comment]
@tderensis @timothy-a-bertram We now have a build directory! This lives in the root, and has our two build scripts (and the third party tools they use) in it. When you run either script, they will create a build/dist directory with the distributable Tacktx.exe and the .dlls it needs to run.

**Comment by rguilmain** [comment]
@tderensis Ideally, I'd like to be able to import middleclass as 'require "third_party.middleclass"'. Currently you have to 'require "third_party.middleclass.middleclass"'. Not sure if you know how to do that; my Googling skills failed me here.

**Comment by tderensis** [comment]
I don't think there is a way to do that, but I made it so you can do: require 'middleclass'

**Comment by rguilmain** [comment]
Okay; I see what you're doing there. Looks better than what I had it set up to do, at least. Closing this card.

**Comment by rguilmain** [comment]
@tderensis Wait, are you sure that works? I'm getting middleclass import issues when I try to run master.

**Comment by tderensis** [comment]
How do you run on windows? What is the exact command? You have to run from
inside the dist directory:
  cd dist
  love Tacktx.love

**Comment by rguilmain** [comment]
Nah, man. I run it from the dist directory, but I don't even have love installed on my computer. build_windows.bat packages it up into an .exe.

**Comment by tderensis** [comment]
OK, then revert that commit and deal with the slightly ugly require
statements for now.

**Comment by rguilmain** [comment]
Done.
